spring:
  datasource:
    dbPg1:
      url: jdbc:h2:mem:todoList
      driverClassName: org.h2.Driver
      username: admin
      password: admin

    dbPg2:
      url: jdbc:h2:mem:todoList
      driverClassName: org.h2.Driver
      username: admin
      password: admin

    dbH2:
      url: jdbc:h2:mem:todoList
      driverClassName: org.h2.Driver
      username: admin
      password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2